/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arreglos.lab;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author David Barreda
 */
public class Pantalla extends javax.swing.JFrame {

    String[] listaPalabras = {"HONDURAS",
        "JAVA",
        "PROGRAMAR",    
        "TECLADO",
        "PANTALLA",
        "VENTANA",
        "CLASES",
        "OBJETOS",
        "JUEGO",
        "COMPUTADORA"};

    Random random = new Random();
    char[] oculta;

    int oportunidades = 0;

    String palabra = listaPalabras[random.nextInt(listaPalabras.length)];

    public Pantalla() {
        initComponents();
        iniciarJuego();
        actualizarLista();
        Listado.setVisible(false);
        jLabel4.setVisible(false);

        oculta = new char[palabra.length()];
        for (int i = 0; i < palabra.length(); i++) {
            oculta[i] = '_';
        }

        actualizarPalabraOculta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        entradaLetra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        palabraOculta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listado = new javax.swing.JList<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("INGRESAR LETRA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 200, 38));

        jButton2.setText("CAMBIAR LISTA DE PALABRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, -1));

        entradaLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaLetraActionPerformed(evt);
            }
        });
        jPanel1.add(entradaLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 94, 28));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PALABRA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese una letra a la vez:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, -1));

        palabraOculta.setForeground(new java.awt.Color(0, 0, 0));
        palabraOculta.setText("_ _ _ _ _ _ _ ");
        jPanel1.add(palabraOculta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Lista de palabras:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 170, 50));

        jScrollPane2.setViewportView(Listado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jugar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void entradaLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaLetraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_entradaLetraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Listado.setVisible(true);
        jLabel4.setVisible(true);
        cambiarPalabras();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    void jugar() {
        String letra = entradaLetra.getText().toUpperCase();
        entradaLetra.setText("");
        

        if (letra.length() != 1 || !Character.isLetter(letra.charAt(0))) {
            JOptionPane.showMessageDialog(this, "SOLO DEBE INGRESAR UNA LETRA VALIDA");
            return;
        }

        char letraIngresada = letra.charAt(0);
        boolean acierto = false;

        for (int i = 0; i < palabra.length(); i++) {
            if (palabra.charAt(i) == letraIngresada && oculta[i] == '_') {
                oculta[i] = letraIngresada;
                acierto = true;
            }
        }

        if (!acierto) {
            oportunidades--;
            JOptionPane.showMessageDialog(this, "La palabra no contiene esa letra. Te quedan " + oportunidades + " intentos.");
        }
        
        actualizarPalabraOculta();

        if (new String(oculta).equals(palabra)) {
            JOptionPane.showMessageDialog(this, "¡Felicidades! Adivinaste la palabra: " + palabra);
            iniciarJuego();
        } else if (oportunidades == 0) {
            JOptionPane.showMessageDialog(this, "Perdiste. La palabra era: " + palabra);
            iniciarJuego();
        }
    }

    void actualizarPalabraOculta() {
        String texto = "";
        for (int i = 0; i < palabra.length(); i++) {
            texto += oculta[i] + " ";
        }
        palabraOculta.setText(texto);
    }

    void iniciarJuego() {
        palabra = listaPalabras[random.nextInt(listaPalabras.length)];
        oculta = new char[palabra.length()];
        for (int i = 0; i < palabra.length(); i++) {
            oculta[i] = '_';
        }
        oportunidades = 5;
        actualizarPalabraOculta();
    }

    void cambiarPalabras() {
        for (int i = 0; i < listaPalabras.length; i++) {
            String nueva = JOptionPane.showInputDialog(this, "Palabra #" + (i + 1) + " actual: " + listaPalabras[i]);
            if (nueva != null) {
                listaPalabras[i] = nueva.toUpperCase();
            }
        }
        Listado.setVisible(false);
        jLabel4.setVisible(false);
        

        actualizarLista();   
        iniciarJuego();      
    }

    public void actualizarLista() {
        String[] textoLista = new String[listaPalabras.length];

        for (int i = 0; i < listaPalabras.length; i++) {
            textoLista[i] = (i + 1) + ". " + listaPalabras[i];
        }

        Listado.setListData(textoLista);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Listado;
    private javax.swing.JTextField entradaLetra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel palabraOculta;
    // End of variables declaration//GEN-END:variables
}
