package equisycero;


import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Selvin Aguilar
 */
public class Juego extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        setLocationRelativeTo(null);
        
        casilla0.setEditable(false);
        casilla1.setEditable(false);
        casilla2.setEditable(false);
        casilla3.setEditable(false);
        casilla4.setEditable(false);
        casilla5.setEditable(false);
        casilla6.setEditable(false);
        casilla7.setEditable(false);
        casilla8.setEditable(false);
        
        
        String jugador2 = "";
        String jugadorActual = ManejoUsuarios.getUsuariologgeado();
        jugador1.setText(jugadorActual);
        
        
        ManejoUsuarios Jugador2juego = ManejoUsuarios.buscarUsuario(jugador2);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_lbl = new javax.swing.JLabel();
        columna_lbl = new javax.swing.JLabel();
        fila_lbl = new javax.swing.JLabel();
        columnainput_txtfield = new javax.swing.JTextField();
        filainput_txtfield = new javax.swing.JTextField();
        casilla2 = new javax.swing.JTextField();
        casilla0 = new javax.swing.JTextField();
        casilla1 = new javax.swing.JTextField();
        casilla3 = new javax.swing.JTextField();
        casilla4 = new javax.swing.JTextField();
        casilla5 = new javax.swing.JTextField();
        casilla6 = new javax.swing.JTextField();
        casilla7 = new javax.swing.JTextField();
        casilla8 = new javax.swing.JTextField();
        INGRESAR = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jugador22 = new javax.swing.JLabel();
        jugador1 = new javax.swing.JLabel();
        fondo_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_lbl.setFont(new java.awt.Font("sansserif", 1, 72)); // NOI18N
        titulo_lbl.setForeground(new java.awt.Color(255, 255, 255));
        titulo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_lbl.setText("TIC TAC TOE");
        getContentPane().add(titulo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 500, 90));

        columna_lbl.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        columna_lbl.setForeground(new java.awt.Color(255, 255, 255));
        columna_lbl.setText("COLUMNA:");
        getContentPane().add(columna_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 130, 70));

        fila_lbl.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        fila_lbl.setForeground(new java.awt.Color(255, 255, 255));
        fila_lbl.setText("FILA:");
        getContentPane().add(fila_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 130, 70));

        columnainput_txtfield.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        getContentPane().add(columnainput_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 140, 40));

        filainput_txtfield.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        getContentPane().add(filainput_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 140, 40));

        casilla2.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 130, 120));

        casilla0.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        casilla0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla0ActionPerformed(evt);
            }
        });
        getContentPane().add(casilla0, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 130, 120));

        casilla1.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 130, 120));

        casilla3.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 130, 120));

        casilla4.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 130, 120));

        casilla5.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 130, 120));

        casilla6.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 130, 120));

        casilla7.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 130, 120));

        casilla8.setFont(new java.awt.Font("sansserif", 0, 75)); // NOI18N
        casilla8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(casilla8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 130, 120));

        INGRESAR.setBackground(new java.awt.Color(0, 102, 255));
        INGRESAR.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        INGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        INGRESAR.setText("INGRESAR");
        INGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(INGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 140, 40));

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 255));
        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Salir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 140, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("JUGADOR 2:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 110, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("JUGADOR 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 110, 20));
        getContentPane().add(jugador22, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 120, 20));
        getContentPane().add(jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 120, 20));

        fondo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg.jpeg"))); // NOI18N
        getContentPane().add(fondo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casilla0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla0ActionPerformed

    private void INGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESARActionPerformed
        jugarTurno();
    }//GEN-LAST:event_INGRESARActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        Menu M=new Menu();
        M.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed
boolean turnoX = true;
    
    private JTextField getCasilla(int pos) {
    switch (pos) {
        case 0: return casilla0;
        case 1: return casilla1;
        case 2: return casilla2;
        case 3: return casilla3;
        case 4: return casilla4;
        case 5: return casilla5;
        case 6: return casilla6;
        case 7: return casilla7;
        case 8: return casilla8;
        default: return null;
    }
}

private void reiniciarTablero() {
    for (int i = 0; i < 9; i++) {
        getCasilla(i).setText("");
    }
    turnoX = true;
}
private void verificarGanador() {
    String[][] tablero = new String[3][3];

    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            int pos = i * 3 + j;
            tablero[i][j] = getCasilla(pos).getText();
        }
    }

    String ganador = null;

    
    for (int i = 0; i < 3; i++) {
        if (!tablero[i][0].isEmpty() && tablero[i][0].equals(tablero[i][1]) && tablero[i][1].equals(tablero[i][2])) {
            ganador = tablero[i][0];
        }
        if (!tablero[0][i].isEmpty() && tablero[0][i].equals(tablero[1][i]) && tablero[1][i].equals(tablero[2][i])) {
            ganador = tablero[0][i];
        }
    }

    
    if (!tablero[0][0].isEmpty() && tablero[0][0].equals(tablero[1][1]) && tablero[1][1].equals(tablero[2][2])) {
        ganador = tablero[0][0];
    }
    if (!tablero[0][2].isEmpty() && tablero[0][2].equals(tablero[1][1]) && tablero[1][1].equals(tablero[2][0])) {
        ganador = tablero[0][2];
    }

    if (ganador != null) {
        JOptionPane.showMessageDialog(this, "¡Jugador " + (ganador.equals("X") ? "1" : "2") + " ha ganado!");
        reiniciarTablero();
        return;
    }

    
    boolean empate = true;
    for (int i = 0; i < 9; i++) {
        if (getCasilla(i).getText().isEmpty()) {
            empate = false;
            break;
        }
    }

    if (empate) {
        JOptionPane.showMessageDialog(this, "¡Es un empate!");
        reiniciarTablero();
    }
}
    private void jugarTurno() {
    int fila, columna;

    try {
        fila = Integer.parseInt(filainput_txtfield.getText());
        columna = Integer.parseInt(columnainput_txtfield.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa números válidos en fila y columna.");
        filainput_txtfield.setText("");
        columnainput_txtfield.setText("");
        return;
    }

    if (fila < 1 || fila > 3 || columna < 1 || columna > 3) {
        JOptionPane.showMessageDialog(this, "Las coordenadas deben estar entre 1 y 3.");
        filainput_txtfield.setText("");
        columnainput_txtfield.setText("");
        return;
    }

    
    int filaIndex = fila - 1;
    int columnaIndex = columna - 1;

    int posicion = filaIndex * 3 + columnaIndex;
    JTextField casilla = getCasilla(posicion);

    if (!casilla.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Esta casilla ya está ocupada.");
        return;
    }

    casilla.setText(turnoX ? "X" : "O");
    turnoX = !turnoX;

    filainput_txtfield.setText("");
    columnainput_txtfield.setText("");

    verificarGanador();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INGRESAR;
    private javax.swing.JTextField casilla0;
    private javax.swing.JTextField casilla1;
    private javax.swing.JTextField casilla2;
    private javax.swing.JTextField casilla3;
    private javax.swing.JTextField casilla4;
    private javax.swing.JTextField casilla5;
    private javax.swing.JTextField casilla6;
    private javax.swing.JTextField casilla7;
    private javax.swing.JTextField casilla8;
    private javax.swing.JLabel columna_lbl;
    private javax.swing.JTextField columnainput_txtfield;
    private javax.swing.JLabel fila_lbl;
    private javax.swing.JTextField filainput_txtfield;
    private javax.swing.JLabel fondo_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador22;
    private javax.swing.JLabel titulo_lbl;
    // End of variables declaration//GEN-END:variables
}